name: Tests
# Tests / Code Coverage workflow runs unit tests and uploads a code coverage report.
# This workflow is run on pushes to chains/nibiru & every Pull Requests where a .go, .mod, .sum have been changed.
on:
  pull_request:
  push:
    branches:
      - chains/nibiru

jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test & Create coverage report
        run: make install test-unit stop-docker-test
      - name: Upload cove coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
